### ISSUE TITLE
Error thrown when using P5.js in instance mode

### ISSUE THREAD

**Issue by grauwald** [jdeboi/p5.mapper#2]
Great library for quick corner pin projection in P5.js - however initially attempted to use this with instance mode instead of global mode and it throws an error `uncaught ReferenceError: mousePressed is not defined`

Did not dig in to find out why this is happening but apparently this lib is expecting global mode and doesn't have an option to instantiate the lib using the sketch reference one would create in instance mode.

**Comment by jdeboi** [comment]
I think I've fixed this, but let me know if anyone else has issues.
